@echo off
echo Starting k6 test visualization environment...
docker-compose up -d influxdb grafana
echo Waiting for InfluxDB and Grafana to start...
timeout /t 5 /nobreak
echo Running k6 tests...
docker-compose run --rm k6
echo Test completed! View results at http://localhost:3000
